# Generated by Django 3.2.11 on 2022-01-20 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('disputed', 'Disputed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('dispatched', 'Dispatched')], default='processed', max_length=10)),
                ('status_message', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('picture', models.ImageField(upload_to='')),
                ('weight_attributes', models.CharField(choices=[('Kg', 'Kg'), ('Piece', 'Piece')], default='Kg', max_length=10)),
                ('availability', models.IntegerField(default=0)),
                ('purchase_price', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=30)),
                ('mobile', models.CharField(max_length=11)),
                ('address', models.CharField(default='', max_length=255)),
                ('ward_no', models.CharField(default='', max_length=50)),
                ('pincode', models.CharField(default='', max_length=10)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('weight', models.CharField(default='', max_length=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='billing.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='billing.product')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='billing.shipping'),
        ),
    ]
