# Generated by Django 3.2.11 on 2022-01-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='weight',
        ),
    ]
