# Generated by Django 3.2.11 on 2022-01-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20220115_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='product',
            name='weight_attributes',
            field=models.CharField(default='', max_length=100),
        ),
    ]
