# Generated by Django 3.2.11 on 2022-01-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20220115_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight_attributes',
            field=models.TextField(default=''),
        ),
    ]
