# Generated by Django 3.2.11 on 2022-01-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_product_weight_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.CharField(default='', max_length=10),
        ),
    ]
