# Generated by Django 3.2.11 on 2022-02-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20220204_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='dbc',
            field=models.CharField(choices=[('DBC-01', 'DBC-01'), ('DBC-02', 'DBC-02'), ('DBC-03', 'DBC-03'), ('DBC-04', 'DBC-04'), ('DBC-05', 'DBC-05'), ('DBC-06', 'DBC-06'), ('DBC-07', 'DBC-07'), ('DBC-08', 'DBC-08'), ('DBC-09', 'DBC-09'), ('DBC-10', 'DBC-10')], default='DBC-01', max_length=10),
        ),
    ]
