# Generated by Django 3.2.11 on 2022-01-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_order_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('processed', 'Processed'), ('disputed', 'Disputed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('dispatched', 'Dispatched')], default='processed', max_length=10),
        ),
    ]
