# Generated by Django 3.2.11 on 2022-02-06 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_dbc'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('weekly', 'Weekly Order')], default='normal', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='weekly_day',
            field=models.CharField(choices=[('', 'No. Not required'), ('Monday', 'Every Monday'), ('Tuesday', 'Every Tuesday'), ('Wednesday', 'Every Wednesday'), ('Thursday', 'Every Thursday'), ('Friday', 'Every Friday'), ('Saturday', 'Every Saturday'), ('Sunday', 'Every Sunday')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
