# Generated by Django 3.2.11 on 2022-02-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20220206_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='sell_price',
            field=models.FloatField(default=0.0),
        ),
    ]
