# Generated by Django 3.2.11 on 2022-01-16 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='billing.shipping'),
        ),
    ]
