# Generated by Django 3.2.11 on 2022-01-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.FloatField(default=0.0),
        ),
    ]
